name: check_linter
on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: lint with pysen
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-python-image .

      - name: run pysen
        run: docker run my-python-image pysen run lint
