name: check_linter
on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: lint with pysen
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-python-image .

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        - name: run pysen
        run: |
          pysen run lint
